CREATE DATABASE QL_MYNGHE;
GO
USE QL_MYNGHE;
GO

--Tạo bảng DANHMUCSANPHAM
CREATE TABLE DANHMUCSANPHAM
(
    MADANHMUC INT IDENTITY(1,1) PRIMARY KEY, 
    TENDANHMUC NVARCHAR(100) NOT NULL, 
);

-- Tạo bảng LOAI
CREATE TABLE LOAI
(	
    MALOAI VARCHAR(10) NOT NULL,
    TENLOAI NVARCHAR(50) NOT NULL,
	MADANHMUC INT,
    CONSTRAINT PK_LOAI PRIMARY KEY(MALOAI),
	CONSTRAINT FK_LOAI_DANHMUCSANPHAM FOREIGN KEY(MADANHMUC) REFERENCES DANHMUCSANPHAM(MADANHMUC)
);

-- Tạo bảng KHUYENMAI
CREATE TABLE KHUYENMAI
(
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    LOAIKHUYENMAI VARCHAR(50),
    TENKHUYENMAI NVARCHAR(100),
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
    GIAMGIA DECIMAL(5,2), 
    CONSTRAINT PK_KHUYENMAI PRIMARY KEY(MAKHUYENMAI)
);

-- Tạo bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP
(
    MANHACUNGCAP INT IDENTITY(1,1) PRIMARY KEY,
    TENNHACUNGCAP NVARCHAR(100) NOT NULL,
    DTHOAI NVARCHAR(20),
    DIACHI NVARCHAR(255)
);

-- Tạo bảng SANPHAM
CREATE TABLE SANPHAM
(
    MASANPHAM VARCHAR(10) NOT NULL,
    TENSANPHAM NVARCHAR(255) NOT NULL,
    HINHANH NVARCHAR(255),
    GIABAN DECIMAL(18,0),
    SOLUONGTON INT,
    MOTA NVARCHAR(1000),
    MALOAI VARCHAR(10),
    MAKHUYENMAI VARCHAR(10),
    MANHACUNGCAP INT,
    CONSTRAINT PK_SANPHAM PRIMARY KEY(MASANPHAM),
    CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY(MALOAI) REFERENCES LOAI(MALOAI),
    CONSTRAINT FK_SANPHAM_KHUYENMAI FOREIGN KEY(MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI),
    CONSTRAINT FK_SANPHAM_NHACUNGCAP FOREIGN KEY(MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP)
);

-- Tạo bảng NGUOIDUNG
CREATE TABLE NGUOIDUNG
(
    MANGUOIDUNG VARCHAR(10) PRIMARY KEY,
    TENNGUOIDUNG NVARCHAR(50) NOT NULL,
    TAIKHOAN VARCHAR(255) NOT NULL UNIQUE,
    MATKHAU NVARCHAR(255) NOT NULL,
    EMAIL NVARCHAR(255),
    SODIENTHOAI NVARCHAR(20)
);

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG
(
    MAKHACHHANG INT IDENTITY(1,1) NOT NULL,
	MANGUOIDUNG VARCHAR(10), 
    HOTEN NVARCHAR(50) NOT NULL,
    SODIENTHOAI VARCHAR(10),
    EMAIL VARCHAR(255),
    CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKHACHHANG),
	FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG (MANGUOIDUNG)
);

-- Tạo bảng DIACHI_GIAOHANG
CREATE TABLE DIACHI_GIAOHANG
(
    MADIACHI INT IDENTITY(1,1) PRIMARY KEY,
    MAKHACHHANG INT NOT NULL,
    DIACHI NVARCHAR(255),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
);
CREATE TABLE HINHTHUCTT
(
	MATT VARCHAR(10) NOT NULL,
	LOAITT NVARCHAR(255),
	CONSTRAINT PK_HTTT PRIMARY KEY(MATT)
);
-- Tạo bảng DONHANG
CREATE TABLE DONHANG
(
    MADONHANG INT IDENTITY(1,1) NOT NULL,
    MAKHACHHANG INT NOT NULL,
	MADIACHI INT NOT NULL, -- Thêm cột MADIACHI để liên kết địa chỉ giao hàng
    NGAYGIAO DATETIME NULL,
    NGAYDAT DATETIME NULL,
    MATT VARCHAR(10),
    GHICHU NVARCHAR(255) NULL,
    TONGSLHANG INT NULL,
    TONGTHANHTIEN DECIMAL(18, 0) NULL,
    TRANGTHAI NVARCHAR(50) DEFAULT 'Chờ xử lý', -- Thêm cột trạng thái đơn hàng
    CONSTRAINT PK_DONHANG PRIMARY KEY(MADONHANG),
    CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	CONSTRAINT FK_DONHANG_DIACHI FOREIGN KEY(MADIACHI) REFERENCES DIACHI_GIAOHANG(MADIACHI),
	CONSTRAINT FK_DONHANG_HINHTHUCTT FOREIGN KEY(MATT) REFERENCES HINHTHUCTT(MATT)
);

-- Tạo bảng CHITIETDONHANG
CREATE TABLE CHITIETDONHANG
(
    MADONHANG INT NOT NULL,
    MASANPHAM VARCHAR(10) NOT NULL,
    SOLUONG INT,
    DONGIA DECIMAL(18,0),
    CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY(MADONHANG, MASANPHAM),
    CONSTRAINT FK_CHITIETDONHANG_DONHANG FOREIGN KEY(MADONHANG) REFERENCES DONHANG(MADONHANG),
    CONSTRAINT FK_CHITIETDONHANG_SANPHAM FOREIGN KEY(MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);


-- Tạo bảng SANPHAM_KHUYENMAI (Bảng nối để quản lý nhiều-nhiều giữa sản phẩm và khuyến mãi)
CREATE TABLE SANPHAM_KHUYENMAI
(
    MASANPHAM VARCHAR(10) NOT NULL,
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    PRIMARY KEY (MASANPHAM, MAKHUYENMAI),
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM),
    FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI)
);

-- Tạo bảng DANHGIA để lưu nhận xét và đánh giá sản phẩm
CREATE TABLE DANHGIA
(
    MADANHGIA INT IDENTITY(1,1) PRIMARY KEY,
    MAKHACHHANG INT NOT NULL,
    MASANPHAM VARCHAR(10) NOT NULL,
    DIEMSO INT CHECK(DIEMSO >= 1 AND DIEMSO <= 5),
    NHANXET NVARCHAR(1000),
    NGAYDANHGIA DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);

-- Tạo bảng QUYEN
CREATE TABLE QUYEN
(
    MAQUYEN VARCHAR(10) PRIMARY KEY,
    TENQUYEN NVARCHAR(50) NOT NULL
);


-- Tạo bảng QUYEN_NGUOIDUNG
CREATE TABLE QUYEN_NGUOIDUNG
(
    MANGUOIDUNG VARCHAR(10),
    MAQUYEN VARCHAR(10),
    PRIMARY KEY (MANGUOIDUNG, MAQUYEN),
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG),
    FOREIGN KEY (MAQUYEN) REFERENCES QUYEN(MAQUYEN)
);




	




